[toolchain]
anchor_version = "1.0.0"

[workspace]
members = ["."]

[programs.devnet]
lendguard_proof_vault = "GQia1ewyLgtkgX7HSfuttJ42qNPpYJhUbxeyCPXtcJFR"

[registry]
url = "https://api.dev.anchor-lang.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/lendguard-devnet.json"

[scripts]
test = "yarn run ts-mocha --timeout 1000000 tests/**/*.ts"

